### ISSUE TITLE
Transactions do not change Holdings

### ISSUE THREAD

**Issue by calgara12** [Xtrendence/Cryptofolio#21]
Hey, first of all thanks for all your hard work. 

Is it possible that when i make a buy transaction, that it automatically gets added to my balance of that coin?

**Comment by Xtrendence** [comment]
Hi, and thank you, glad you're enjoying it! :)

I could definitely add that as a changeable option in settings. The reason I didn't is because letting you manually change the holdings themselves on top of allowing you to record transactions meant that one would have to override the other, and I couldn't decide which one. The other portfolio apps don't seem to even allow you to modify holdings directly without a transaction and I actually found that annoying. 

I'll look into it though and think of something. Perhaps a toggle in settings that lets you choose whether transactions get mixed with holdings, don't affect it at all, or if they override it completely.

**Comment by calgara12** [comment]
Yeah a toggle would be great!

**Comment by Xtrendence** [comment]
I've added this to the project board as a [card](https://github.com/Xtrendence/Cryptofolio/projects/1#card-60332519), so I'll close this issue. If you have more requests or any bugs etc. then please don't hesitate to open more issues. Thank you! :)
