### ISSUE TITLE
Suggestion: multi-account tracking

### ISSUE THREAD

**Issue by Chinoman10** [Xtrendence/Cryptofolio#25]
Hi there :)

I'd like to leave a simple suggestion:
Make the login and storage system capable of managing multiple users. I may be wrong, but I believe this project currently only supports one main account per installation, correct?

I think this could be a must-have for some people, but most of them aren't tech-savvy enough, so having one "IT friend" in the bunch would be enough for all of them to benefit from the cryptofolio tracking.

Kind regards.

**Comment by Xtrendence** [comment]
Hi! :)

That's a wonderful idea, I'll add it to the project board in a bit. I'll add the feature where transactions can optionally affect holdings, and then I'll get started on user accounts. What I might do is add a dropdown in settings to choose which portfolio you're viewing and an option to create a new one, so the account and password would be the same, but you'd be able to switch between different portfolios which would have a different set of activities and holdings.

**Comment by Chinoman10** [comment]
But wouldn't in that case, one instance still be tied to one single account?
The purpose of my suggestion is to have a cryptofolio "service" which you can provide to your friends and family.
Let's say I deployed your site/app, to one of my domains, and then I tell my friends to track their portfolios via my website. They'd need to register, log in, and then add their details (potentially I could do the registration for them at first, as long as they could change their PW afterward).
I've been using [CoinMarketCap's Portfolio Tracker](https://coinmarketcap.com/portfolio-tracker/), but it lacks some features like being able to swap cryptos from one to another. It only supports buying and selling Crypto with Fiat, so if I swap ETH for BTC for example, I need to "sell" ETH for a certain fiat price and then buy BTC at the equivalent price, which is retarded...

**Comment by Xtrendence** [comment]
Ahhh, I see, so you want to allow them to log in as well. I could definitely add user accounts where you'd register them and then give them the login credentials, but making a registration and stuff would sort of go outside the scope of the project which is to be a self-hosted portfolio for one user. I'd also have to add a ton more validation checks as currently the whole thing works on the basis that you wouldn't purposefully try to break or corrupt your data by sending the API deliberately malicious or otherwise invalid data. 

So keeping that in mind, I'll add user accounts and you'd be able to make more accounts from the settings page (and they'd be able to change their password afterwards as you said), but I'd urge you to only give the login credentials to people you trust, as they might be able to mess with your data if they tried, although I'll obviously do my best to prevent that, but it's just worth keeping in mind that this isn't meant to be a publicly accessible thing. I don't immediately see any security issues as they wouldn't have access to your session tokens, so it's not like they'd be able to modify your data, but I'd still be careful just in case.

**Comment by Chinoman10** [comment]
I appreciate the disclaimer 😏 
Thanks for the effort! I'll definitely give it a go when you add those features in :)
