### ISSUE TITLE
Question: portfolio gains/losses?

### ISSUE THREAD

**Issue by poblabs** [Xtrendence/Cryptofolio#32]
Is it possible in a future release to add what we bought the crypto at so that we can track overall gains/losses? This is an interesting question though since some assets are mined assets which have no FIAT cost to them relative to buying crypto. Not sure what makes sense - thoughts?

**Comment by Xtrendence** [comment]
Hi, yes it's possible to add something like this (hopefully). I'm currently on holiday, but I'm working on a way to get historical market data for assets the user holds without exceeding CoinGecko's API limits. I don't think I'll add mining/staking support, but it'll basically be a chart over a time span representing the user's overall holdings value each day. This would only work if holdings are based on transactions though (an option that'll be changeable in the settings).

**Comment by poblabs** [comment]
I noticed coingecko has a portfolio option now, and they allow you to enter in coin price, coin qty and then they use that to chart. They don't appear to be pinging their API for the pnl, just the math on the change of the current price. Perhaps this is an easier approach and also more API friendly. Just a thought

**Comment by Xtrendence** [comment]
Yeah that's a fair point. Their API does have an endpoint where you can pass it a list of coin IDs and get the current price and some additional info about said coins, but the issue is that it'd only be the difference between when you bought and the present, but I want users to be able to see how their assets have performed since they boutht them, so like a chart from when they bought until the present day with daily intervals or something. There's two ways I'm considering, but each has a drawback. 

The first would be to simply save the overall portfolio value of a user every 24h using a background task, but the downside is that it'd only be doable on the mobile app and desktop app, but not the web interface, and the user may not have network access for a day, or simply not use the web interface for that day, which would mean the chart would have missing days.

The other option, which is likely what I'll go with, is to save the current price of every asset the user has in their portfolio using the API endpoint I mentioned, and fetching the historical market data of each asset when the user first adds it to their holdings. Then, when the user wants to view the chart, there'd be a quick check to ensure there aren't any missing dates. If there are, then unfortunately there'll have to be a loading screen (I'll include a progress bar) while the API requests are made with a delay between them to avoid hitting the rate limit. What I could do to make this scenario less likely to occur is to also have a background task that sends a request to Cryptofolio's API to perform these checks while the user isn't using the app, that way the latest market data is always available. 

I'll have to see once I actually start coding it, but the second approach seems the most robust and would provide the most functionality, so it's what I'm leaning towards.

**Comment by poblabs** [comment]
Cool! Looking forward to it. Thanks for thinking about it
