### ISSUE TITLE
Can't add any assets

### ISSUE THREAD

**Issue by eralardz** [Xtrendence/Cryptofolio#33]
Hello,

I just installed this app on a LAMP-stack. Most things work fine, but I can't add any assets. I always get "Couldn't add that coin. Try adding by ID". See screenshot below.

I tried different things (e.g. manually populating coins.json) but I can't get it to work.

<img width="704" alt="Schermafbeelding 2021-06-15 054749" src="https://user-images.githubusercontent.com/3121272/121989978-52582500-cd9d-11eb-8fa1-ea2fd53d155d.png">

**Comment by Xtrendence** [comment]
Hi, I'm on holiday right now so debugging isn't really possible for another few days. May I ask if you downloaded the API using the source code ZIP from the Releases or by downloading the whole project from the main page? Ensure your app and the API are both downloaded from the same release tag so that they're compatible. Other than that, I'm not sure why this could be happening as you've already logged in and such, so writing/reading files would be working fine. Could you also confirm whether or not the Market page works just to make sure the CoinGecko API interaction is functioning? Thank you. :)

**Comment by eralardz** [comment]
No worries, enjoy your holiday! 

I used the source code zip from releases. The market page also works fine, so the CoinGecko API is fine I think.

**Comment by Xtrendence** [comment]
Thank you! :) 

And I'm guessing based on what you've tried, the coins.json file doesn't get filled automatically? If that's the case, then it's definitely an API issue and the coins/read.php isn't working as expected. Could you maybe try changing your password as well and confirm that that works? Also, do you know your PHP version? If we can't figure it out then yeah, after my holiday I'll test everything on Linux and see what's up.

Best guess, it's something unique to this situation, like maybe a problem with either PHP incompatibility or some sort of permission issue maybe as it seems to work fine on Windows and macOS (and a Docker image running Linux).

**Comment by eralardz** [comment]
That's right, the coins.json file is empty. 

I tried changing my password, and that works correctly. Settings.json is filled as it should.
My PHP version:
`root@5d1bfbc33024:/var/www/html/api/data# php -v
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies
`
I'm running a LAMP-stack (https://hub.docker.com/r/ownyourbits/lamp-arm) on a Raspberry Pi 4.
Perhaps I should try another environment?

**Comment by Xtrendence** [comment]
Hi, could you replace your api/coins/read.php file with this one and see if it works fine? I've tested a bunch of things, and it all works fine, so I'm sort of guessing that maybe the fetchCoins() function isn't getting called when logging in for some reason. This version of read.php checks to ensure the coin list is available each time a request is made to it. 

[Fix.zip](https://github.com/Xtrendence/Cryptofolio/files/6679569/Fix.zip)

**Comment by Xtrendence** [comment]
If it works, then I'll commit that and close the issue, and the fix will be included in the next update.

**Comment by Xtrendence** [comment]
I'll close this issue since there hasn't been an update in two weeks, but if you're still having this issue, then please reopen it and I'll take a closer look. Currently, the PHP file I sent in the comment 9 days ago has replaced the original and the code's been committed to the main branch, so anyone downloading the API from main right now shouldn't run into the issue you described (hopefully).
