### ISSUE TITLE
[FR] CeFi platform API support

### ISSUE THREAD

**Issue by Hukuma1** [Xtrendence/Cryptofolio#44]
CeFi platforms like BlockFi, Celsius, Nexo, Crypto.com etc are gaining traction. I know many crypto enthusiasts earn yield on their holdings. Would love to see Cryptofolio be able to pull and add these weekly/monthly payouts automatically.

Right now it seems only Celsius has an API for this feature in place.

<img width="241" alt="celsiusapi" src="https://user-images.githubusercontent.com/54511555/123694099-bce17a00-d80d-11eb-9124-296146a62d06.png">

**Comment by Xtrendence** [comment]
Hi, I've looked into adding support for both exchanges and platforms that pay users for keeping their crypto on there, but unfortunately they all have massively different APIs, and I alone can't maintain them and keep an eye on them for changes, which would be a lot of work on top of having to code support for all of them, and if I add 1 then it'd be unfair to reject others. I [replied to someone else on Reddit](https://www.reddit.com/r/selfhosted/comments/o9qt1k/released_v210_of_cryptofolio_an_opensource/h3cxsw9/?context=3) explaining all this further. I apologize for not being able to add this, it's sort of a Pandora's box where if I start adding support for one external platform, I'll eventually get requests for a lot of others.

**Comment by Hukuma1** [comment]
No worries, makes sense. Maybe there could be some plugin system down the road so that others could maintain it? This way the burden isn't on you for constant upkeep of different platform API stuff.

**Comment by Xtrendence** [comment]
Absolutely. While I don't accept pull requests that modify the main functionality of the software (I already had a team project over the past year, so this is sort of like my "here's what I can do alone" project for my CV), I am completely open to plugins being developed by others and linked to on the Wiki page of this repo or something. I could add the foundation for the API to fetch data from other exchanges and platforms, and make it so as long as the plugin's output data is compatible with what Cryptofolio's API expects, then you could just drag and drop a PHP file into a new /api/plugins/ folder and be done with it. Since it's not a popular project, I don't imagine plugin developers would be that active or easy to find, but at least the option would be there for anyone who decides to do it. Thank you for the suggestion, that's definitely a manageable approach.
