### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [Xtrendence/Cryptofolio#46]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by Xtrendence** [comment]
Thank you for pointing this out. Since you know more about this, you could probably help me pick a license for my situation. 

For my next year of university, I'll be using this project as a foundation for my final year individual project. As such, the code must entirely be my own as it'd count as plagiarism per our university guidelines. Aside from that, since I already have a massive team project from my 2nd year, I want this to be like a contrasting "and here's what I can do on my own" sort of thing, so I'd encourage people to request features and point out bugs rather than fix it for me. Since this is also meant to be a learning experience, I want to practice investigating bugs, reproducing them, and fixing them, rather than having someone else do it for me. As far as copyright goes, the ideal license would be one that allows people to modify Cryptofolio and make their own version, but still credit me if big portions of the code are mine. 

So considering this, what license would you recommend? And thank you again, your help is much appreciated man! :)

**Comment by Xtrendence** [comment]
Thank you for the help! I'll make sure to add both of those.
