### ISSUE TITLE
when starting the image-permission denied

### ISSUE THREAD

**Issue by jboesh** [Xtrendence/Cryptofolio#51]
Hi

I get the following error when trying to start the docker image:
/usr/local/bin/docker-php-entrypoint: 9: exec: start-apache: Permission denied                                                                                                                                                                                       

any idea why this is happening?
Iam using your docker compose example.
Thanks

**Comment by Xtrendence** [comment]
It might be because I haven't actually built an image since I merged the pull request that added docker-compose support, so the current image that's on DockerHub likely doesn't support it. I'm a bit busy with personal stuff this week, but I'll get around to figuring out how it works and update the image to support it too. Thank you for bringing this to my attention though, I'll make sure that start-apache script works.

**Comment by Xtrendence** [comment]
The script wouldn't run for me either until I changed the line endings. Could you try pulling the image using `docker pull xtrendence/cryptofolio:latest` and confirm that works? Thank you.

**Comment by Xtrendence** [comment]
I'll close this for now as I think the issue should be fixed since the latest Docker image seems to be working fine for everyone. If the issue persists though, then please reopen the issue. Thank you.

**Comment by jboesh** [comment]
what adjustment have you made in the apache files and/or docker file? the image works when I pull it from dockerhub but not yet from the dockerfile in your github

**Comment by Xtrendence** [comment]
I'm not entirely sure what could cause this then. Could you maybe add this before the CMD line in the Dockerfile and quickly test it to see if it fixes it? I don't know if it'll work but it usually fixes any permission issues I've had with shell scripts in the past. 

`RUN ["chmod", "+x", "/usr/local/bin/start-apache`
