### ISSUE TITLE
Docker image not up to date

### ISSUE THREAD

**Issue by nitorrep** [Xtrendence/Cryptofolio#60]
Hi  !
Could you update the docker image on dockerhub?
Thank you in advance !

**Comment by Xtrendence** [comment]
Hi there! :)

The latest release is V.2.1.0 which is already on DockerHub. I'm currently working on V.2.2, and you can track its progress using the [Project Board](https://github.com/Xtrendence/Cryptofolio/projects/1). It's about halfway done, but the last few features are quite a lot more complex than the first few, so they'll take some more time.

**Comment by nitorrep** [comment]
Thank you for your fast answer !
I'm running the latest docker image and I do not see the CHF support, is it normal?

**Comment by Xtrendence** [comment]
Yes that's normal, unfortunately additional currency support is part of V.2.2, so you'll have to wait a bit for it, I apologize for that. Good news is that at the latest, I'll release the update during the first week of September as I'm starting my next year of university, and might not have much time to spend on Cryptofolio, so I'd rather make another update containing all the stuff I've added since the last release, and since I've already finished coding the additional currency support, that'd be 100% included.

**Comment by Xtrendence** [comment]
By the way, just making sure I got it right, but for CHF, would I write the prices as, for example "Fr 45,600"?

**Comment by nitorrep** [comment]
No need to apologize, it's already an awesome work and your project is on my watch list, I will wait. 
Usually we would more use 45'600.00 but 45,600 is perfectly fine.
For the symbol we use either Fr or CHF

**Comment by Xtrendence** [comment]
Thank you for the compliment! I'd use `'` as a thousand separator, but I've coded things in such a way that some parts of the software look for and replace commas when converting between strings and int/float as I didn't think back then that this would become an issue. In the future, I may add a setting to allow users to change which separator they want to use, but for now it'll stay as a comma until I add everything else. I'll close this issue, and comment back here when I release V.2.2 just as a reminder. Have a great day! :)
