### ISSUE TITLE
latest docker image issue

### ISSUE THREAD

**Issue by GPConnect** [Xtrendence/Cryptofolio#65]
Tried the latest release for the api and getting this ! 
status : restarting
docker logs : 
"/usr/bin/env: 'bash\r': No such file or directory"

**Comment by tibuski** [comment]
Hello,
Just updated my docker image and have the exact same issue :

`nuc:~$ sudo docker start cryptofolio && sudo docker logs -f cryptofolio
cryptofolio
/usr/bin/env: 'bash\r': No such file or directory
/usr/bin/env: 'bash\r': No such file or directory
/usr/bin/env: 'bash\r': No such file or directory
/usr/bin/env: 'bash\r': No such file or directory
/usr/bin/env: 'bash\r': No such file or directory
/usr/bin/env: 'bash\r': No such file or directory
/usr/bin/env: 'bash\r': No such file or directory
/usr/bin/env: 'bash\r': No such file or directory
/usr/bin/env: 'bash\r': No such file or directory
/usr/bin/env: 'bash\r': No such file or directory
/usr/bin/env: 'bash\r': No such file or directory
/usr/bin/env: 'bash\r': No such file or directory
`

**Comment by GPConnect** [comment]
also, what will be your username on the new release if we already add an account on last version ?
admin ?

**Comment by Hukuma1** [comment]
+1 :(

**Comment by Xtrendence** [comment]
Thank you for bringing this up, it's been fixed now hopefully. Damn Windows always gotta ruin things with those line endings. 

And @GPConnect you are indeed correct, the username is "admin" on the new release. I've added this to the README as well. I'd recommend maybe exporting your data and importing it to the new one if you don't want to deal with moving the JSON files around. Otherwise, just make sure you don't use your old `account.json` file as the new one has the username in it and won't work without it. 

Thank you! :) Have a good day.

**Comment by Xtrendence** [comment]
Do report back on whether or not its fixed so I can close the issue if it is.

**Comment by tibuski** [comment]
Thank you for the quick reaction !
I confirm the docker started without issue, I just lost my historical data :)
If I just started the new docker pointing to my usual data directory I guess it overwrited the old json ?

**Comment by tibuski** [comment]
Nevermind, copy json files except account.json and it works now !
One small issue I just noticed, I can't switch to dark mode it says : couldn't remove css

**Comment by tibuski** [comment]
Thank you for your quick reaction ! 

Docker works, copy json files works too.
I just had to restart the docker to have CSS working.

**Comment by Xtrendence** [comment]
That's excellent to hear! Let me know if there are any other bugs or issues and I'll take a look. Have a great day. :)
