### ISSUE TITLE
Docker: Function not implemented: AH00141: Could not initialize random number generator

### ISSUE THREAD

**Issue by ituri** [Xtrendence/Cryptofolio#66]
Hi,

I tried to run the docker container but I keep getting the following error when starting it:
`[Thu Sep 09 07:52:11.105095 2021] [:crit] [pid 11] (38)Function not implemented: AH00141: Could not initialize random number generator`

Is there a way to solve this problem?

Thanks!

**Comment by Xtrendence** [comment]
Hi, apparently it seems it can be an issue with your system's PATH environment variable having possibly invalid characters:

https://stackoverflow.com/questions/17884176/apache-could-not-initialize-random-number-generator

I'm afraid I can't really help beyond that as the issue seems to be the host OS rather than Docker itself or the Cryptofolio Docker image. 

Someone else pointed out that you could be missing `urandom` and `random`:

https://stackoverflow.com/questions/22185207/ubuntu-12-10-apache-2-4-6-ah00141-could-not-initialize-random-number-generator

Good luck, and if it does turn out to be an issue with the Cryptofolio images, then please do post the solution and I'll try to push a fixed image.

**Comment by ituri** [comment]
Unfortunately, you're right: It seems that my host system (Synology DSM 7.0) is the problem here. I've found similar posts from other problems which run into the same problem (https://www.reddit.com/r/synology/comments/j5770x/apache_rng_error_any_help/).

So I guess there's nothing I can do on my side. :(

**Comment by Xtrendence** [comment]
That sucks to hear man, maybe if you get like a cheap Raspberry Pi or something, then you could use that for all your Docker needs as I'm sure other projects that use random number generators will have this issue too. It's strange to me that an OS would even have this issue since RNG is a big deal when it comes to anything security related, unless it's just that their implementation of it isn't compatible with Docker or something. Anyway, have a good day man, hopefully you figure out a workaround that doesn't cause too much of a headache for you.
