### ISSUE TITLE
White bar in settings page of android app.

### ISSUE THREAD

**Issue by baduhai** [Xtrendence/Cryptofolio#67]
There is a seemingly random white bar in the settings page of the android app, just above the navbar.
![Screenshot_20210909-130818_Cryptofolio](https://user-images.githubusercontent.com/31864305/132675682-679342fd-3341-4499-9254-f9dbf9f259b6.jpg)

**Comment by Xtrendence** [comment]
That's very strange... It wasn't there on my Android emulator or my actual phone. 

Could you confirm a few things for me?

1) Your phone model.

2) Android OS version.

3) Does it go away when you scroll down?

4) Is it there on the Dashboard page when you have a bunch of holdings such that you can scroll up and down on the whole Dashboard page?

5) If you had the app before V.2.2, was it there or is this a new thing?

Thank you. Sorry for all the questions, but since it's not happening for me I can't really test things to see what it could be. Hopefully with your phone model and OS, I can get it to show up in an identical emulator.

**Comment by baduhai** [comment]
Don't worry about asking so many questions, I shouldn't have been an idiot and given more info on the original bug report.

1. Galaxy S9+
2. Android 10
3. It does not go away when scrolling down, it is above the ScrollView elements.
4. I don't understand the question, the white bar is only present in the settings page. It is also there when using a light theme, but not as visible, as it blends in.
5. It is present at least as far back as version 2.1.

**Comment by Xtrendence** [comment]
Nah it's okay man.

For question 4, I ask because the settings page and dashboard page are the only pages where you can scroll the whole page as opposed to just a list on the page, so I was wondering if the issue was on the dashboard as well. I suppose it's good that it's not, as I can see what I coded differently on the settings page. I can think of a few things to try. I'll reply to this issue in a bit with a few different APK files, could you then perhaps tell me which one fixes the issue (or none if that's the case)? That'd be very helpful, thank you! :)

**Comment by baduhai** [comment]
Yeah, no problem. I actually tried forking your code and looking for the problem on my own, and while I didn't try particularly hard, I didn't know how to get node set up so that android studio could build the app. Having a short readme on the app folder with some brief build instructions would make contributions a lot easier.

**Comment by Xtrendence** [comment]
[Cryptofolio-MarginFix.zip](https://github.com/Xtrendence/Cryptofolio/files/7137310/Cryptofolio-MarginFix.zip)

Could you confirm if this fixes it?

As for contributions, unfortunately I can't accept pull requests because I'm planning on reusing a lot of code and basing my final year university project on Cryptofolio, and the uni has a strict plagiarism policy, so I don't know if I'm allowed to have anyone contribute any code. That's why all the existing contributions are related to either Docker stuff, or API hosting etc. rather than anything involving the actual codebase.

**Comment by baduhai** [comment]
Unfortunately it doesn't fix it. 

I understand your point on contributions, that's fair enough.

**Comment by Xtrendence** [comment]
[Cryptofolio-HeightFix.zip](https://github.com/Xtrendence/Cryptofolio/files/7137764/Cryptofolio-HeightFix.zip)

Okay, I think this time I got it. :)

**Comment by baduhai** [comment]
You got it! Thanks for the very quick fix!

**Comment by Xtrendence** [comment]
Sure thing man, have a good day! :) Thank you again for bringing this up.
